name: PubMed Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    # Step 3: Install Chrome
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # Step 4: Install dependencies
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install chromedriver-autoinstaller

    # Step 5: Run the PubMed scraper
    - name: Run PubMed scraper
      run: |
        xvfb-run --auto-servernum -- python pmid_webscraper.py
