name: Scrape PubMed Data

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  scrape-pubmed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Set up Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4 wget
        sudo apt-get install -y chromium-browser

        # Find the installed Chrome version
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        
        # Get the matching ChromeDriver version for the installed Chrome
        DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")

        # Download and install the matching ChromeDriver
        wget -N https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Run PubMed Scraper
      run: |
        xvfb-run --auto-servernum -- python pmid_webscraper.py  # Ensure this matches the name of your script

    - name: Upload CSV file
      uses: actions/upload-artifact@v3
      with:
        name: scraped-pubmed-data
        path: ./output/pmid_list_master.csv
