name: Scrape PubMed Data

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  scrape-pubmed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Set up Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4 wget
        wget -N https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        rm chromedriver_linux64.zip
        sudo apt-get install -y chromium-browser
        if [ ! -L /usr/bin/google-chrome ]; then sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome; fi  # Check for existing link

    - name: Run PubMed Scraper
      run: |
        xvfb-run --auto-servernum -- python pmid_webscraper.py

    - name: Upload CSV file
      uses: actions/upload-artifact@v3
      with:
        name: scraped-pubmed-data
        path: ./output/pmid_list_master.csv
