name: Scrape PMIDs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python scripts/scrape_pmid.py

    - name: Upload output CSV file
      uses: actions/upload-artifact@v3
      with:
        name: pmid-list-csv
        path: output/pmid_list_master.csv
